version: "2"
services:
    web:
        tty: true
        stdin_open: true
        build: .
        volumes:
            - ./:/app
        command: "/bin/bash"
        ports:
            - "8080:8080"
    mongo:
        image: mongo
        ports:
            - "27017:27017"